version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "443:443" 
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/OpaqueRedirectionBug.crt:/etc/ssl/certs/site.crt
      - ./nginx/OpaqueRedirectionBug.key:/etc/ssl/private/site.key
    restart: always

  api:
    depends_on:
      - reverseproxy 
    build:
      context: ./OpaqueRedirectionBug
    environment:
      - ASPNETCORE_URLS=http://*:5001      
    ports:
      - "5001:5001"  
    restart: always